apiVersion: v1
kind: Service
metadata:
  labels:
    name: webapp
  name: webapp
  namespace: default∏
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    name: webapp
  type: ClusterIP

