apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp
spec:
  replicas: 3
  template:
    metadata:
      name: webapp
      labels:
        name: webapp
    spec:
      containers:
      - image: tomcat
        name: webapp
        ports:
        - name:  webapp
          containerPort: 8080