apiVersion: v1
kind: Service
metadata:
  name:  frontend
  labels:
    name: frontend
spec:
  type:  NodePort
  ports:
  - name:  frontend
    port:  80
    nodePort:  30001
  selector:
    name: frontend