apiVersion: v1
kind: PersistentVolume
metadata:
  name: data02
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/k8s/data02
    server: 192.168.56.103