apiVersion: v1
kind: PersistentVolume
metadata:
  name: data03
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/k8s/data03
    server: 192.168.56.103