apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
    - image:  tomcat
      name:  tomcat
      ports:
      - containerPort: 8080
      volumeMounts:
      - name:  app-logs
        mountPath:  /usr/local/tomcat/logs
    - name: busybox
      image: busybox
      command: ["sh","-c","tail -f /logs/catalina*.log"]
      volumeMounts:
      - name: app-logs
        mountPath: /logs
  volumes:
  - name: app-logs
    emptyDir: {}