apiVersion: v1
kind: Pod
metadata:
  name: cm-test-app
spec:
  containers:
  - image:  busybox
    name:  cm-test-app
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name:  serverxml
      mountPath:  /configfiles
  volumes:
  - name:  serverxml
    configMap:
      name: cm-appconfigfiles
      items:
      - key: key-serverxml
        path: server.xml
      - key: key-loggingproperties
        path: logging.properties  