apiVersion: v1
kind: Pod
metadata:
  name: cm-test-app1
spec:
  containers:
  - image:  busybox
    name:  cm-test-app1
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name:  serverxml
      mountPath:  /configfiles
  volumes:
  - name:  serverxml
    configMap:
      name: cm-appconfigfiles1
