apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 1
  template:
    metadata:
      name: php-apache
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: googlecontainer/hpa-example
        resources:
          requests:
            cpu: 50m
        ports:
        - containerPort: 80
